# Creamos una imagen docker basada en la imagen oficial de FRR (que es en base Debian/Ubuntu).
FROM frrouting/frr:latest

# Instalamos y borramos caches para no dejar basura en la imagen.
RUN apt-get install -y --no-install-recommends iputils-ping iproute2 bash busybox
RUN rm -rf /var/lib/apt/lists/*

# Copiamos los ficheros de configuración de FRR (contiene zebra, ospfd, bgpd y isisd).
COPY frr/daemons /etc/frr/daemons
COPY frr/frr.conf /etc/frr/frr.conf

# Arranca FRR
CMD ["/usr/lib/frr/docker-start"]