services:
  # ----------------------- DOCKERS ----------------------- #

  server:
    container_name: server
    build:
      context: ./P1
      dockerfile: Dockerfile
    restart: unless-stopped

# ------------------------- VOLUMES ------------------------ #

# ------------------------- NETWORK ------------------------ #
