#!/bin/sh
# Leaf router (router-4) - bridge + vxlan + FRR adjustments

ip link add br0 type bridge
ip link set dev br0 up
ip link set dev eth3 up
ip addr flush dev eth3

# Create vxlan with explicit local underlay IP
ip link add vxlan10 type vxlan id 10 local 10.1.1.10 dev eth3 dstport 4789
ip link set dev vxlan10 up

brctl addif br0 vxlan10
brctl addif br0 eth3

# Assign underlay IP to bridge
ip addr add 10.1.1.10/30 dev br0
# Loopback for router-id and BGP source
ip addr add 1.1.1.4/32 dev lo

# FRR config using br0
vtysh -c 'configure terminal' \
      -c 'interface br0' \
      -c 'ip address 10.1.1.6/30' \
      -c 'ip ospf area 0' \
      -c 'interface lo' \
      -c 'ip address 1.1.1.3/32' \
      -c 'ip ospf area 0' \
      -c 'router ospf' \
      -c 'router-id 1.1.1.3' \
      -c 'router bgp 1' \
      -c 'bgp router-id 1.1.1.3' \
      -c 'neighbor 1.1.1.1 remote-as 1' \
      -c 'neighbor 1.1.1.1 update-source lo' \
      -c 'address-family l2vpn evpn' \
      -c 'neighbor 1.1.1.1 activate' \
      -c 'advertise-all-vni'
