FROM frrouting/frr:latest

#busybox
RUN apk add --no-cache iputils bridge bash

ENV DAEMONS="zebra bgpd ospfd isisd"
#this command create empty conf files for all of the daemons
RUN touch /etc/frr/bgpd.conf /etc/frr/ospfd.conf /etc/frr/isisd.conf \
    && chown frr:frr /etc/frr/*.conf \
    && chmod 640 /etc/frr/*.conf
RUN echo -e "zebra=yes\nbgpd=yes\nospfd=yes\nisisd=yes\n" > /etc/frr/daemons

CMD /usr/lib/frr/watchfrr -d zebra bgpd ospfd isisd && tail -f /dev/null
#start the daemons in background && keep the container up

#routing services:
#   -bgpd:  protocol to exchange routes between autonomous systems (Internet).
#   -ospfd: internal routing protocol that calculates the shortest path.
#   -isisd: internal routing protocol used in large and scalable networks.
#   -zebra(not a routing service) (orchestrator): internal route manager that applies routes from daemons to the kernel.

