services:
  # ----------------- WEB SERVER (80, 443) ----------------- #

  nginx:
    container_name: nginx
    build:
      context: ./backend/nginx
      args:
        - HOST_NAME=${HOST_NAME-localhost}
    ports:
      - "8443:443"
    networks:
      - public-net
    restart: unless-stopped

  # --------------------- WEB PAGE (80) -------------------- #

  web:
    container_name: web
    build:
      context: ./frontend/web
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/web:/app
    networks:
      - public-net
    restart: unless-stopped

  # -------------------- GATEWAY (3000) -------------------- #

  gateway:
    container_name: gateway
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/gateway/src:/app/src
    environment:
      - SERVICE_URL=gateway:3000
      - CORS_ORIGIN=${CORS_ORIGIN-*}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL-http://oauth:4000}
      - GAME_SERVICE_URL=${GAME_SERVICE_URL-http://game:4002}
    networks:
      - public-net
      - service-net
    restart: unless-stopped

  # --------------- MICRO-SERVICES --------------- #

  # Stats (4000)
  stats:
    container_name: stats
    build:
      context: ./backend/services/stats
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/services/stats/src:/app/src
      - ms_stats_data:/app/data
    environment:
      - SERVICE_URL=game:4000
    networks:
      - service-net
    restart: unless-stopped

  # OAuth (4000)
  oauth:
    container_name: oauth
    build:
      context: ./backend/services/oauth
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/services/oauth/src:/app/src
    environment:
      - SERVICE_URL=oauth:4000
      - STATS_URL=stats:4000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_REDIRECT=${GOOGLE_CLIENT_REDIRECT}
      - FORTYTWO_CLIENT_ID=${FORTYTWO_CLIENT_ID}
      - FORTYTWO_CLIENT_SECRET=${FORTYTWO_CLIENT_SECRET}
      - FORTYTWO_CLIENT_REDIRECT=${FORTYTWO_CLIENT_REDIRECT}
    networks:
      - service-net
    restart: unless-stopped

  # Game (4002)
  game:
    container_name: game
    build:
      context: ./backend/services/game
      dockerfile: Dockerfile
    volumes:
      - ./backend/services/game/src:/app/src
    environment:
      - SERVICE_URL=game:4002
      - STATS_URL=stats:4000
    networks:
      - service-net
    restart: unless-stopped

# ------------------------- VOLUMES ------------------------ #

volumes:
  ms_stats_data:

# ------------------------- NETWORK ------------------------ #

networks:
  public-net:
    name: public-net
    driver: bridge
  service-net:
    name: service-net
    driver: bridge
