#!/bin/sh
# Leaf router (router-4) - bridge + vxlan + FRR adjustments

ip link add br0 type bridge
ip link set dev br0 up
ip link set dev eth0 up
ip link set dev eth3 up
ip addr flush dev eth3

# Create vxlan with explicit local underlay IP
ip link add vxlan10 type vxlan id 10 local 1.1.1.4 dstport 4789
ip link set dev vxlan10 up

brctl addif br0 vxlan10
brctl addif br0 eth0

# Assign underlay IP to uplink
ip addr add 10.1.1.10/30 dev eth3
# Loopback for router-id and BGP source
ip addr add 1.1.1.4/32 dev lo

# FRR config
vtysh <<EOF
configure terminal
!
interface eth3
 ip ospf area 0
 ip ospf network point-to-point
!
interface lo
 ip ospf area 0
!
router ospf
 router-id 1.1.1.4
 passive-interface lo
!
router bgp 1
 bgp router-id 1.1.1.4
 neighbor 1.1.1.1 remote-as 1
 neighbor 1.1.1.1 update-source lo
 address-family l2vpn evpn
  neighbor 1.1.1.1 activate
  advertise-all-vni
 exit
!
end
write memory
EOF
