#!/bin/sh
# Leaf router (router-3) - bridge + vxlan + FRR adjustments

ip link add br0 type bridge
ip link set dev br0 up
ip link set dev eth0 up
ip link set dev eth2 up
ip addr flush dev eth2

# Create vxlan with explicit local underlay IP (the address we will put on br0)
ip link add vxlan10 type vxlan id 10 local 1.1.1.3 dstport 4789
ip link set dev vxlan10 up

brctl addif br0 vxlan10
brctl addif br0 eth0

# Assign underlay IP to the uplink (routed underlay)
ip addr add 10.1.1.6/30 dev eth2
# Loopback for router-id and BGP source
ip addr add 1.1.1.3/32 dev lo

# FRR configuration (load via vtysh -f)
vtysh -f /home/jmartos-/Documents/42_WorkSpace/P3/_42user-3.frr
