#!/bin/sh
# Leaf router (router-4) - bridge + vxlan + FRR adjustments

ip link add br0 type bridge
ip link set dev br0 up
ip link set dev eth0 up
ip link set dev eth3 up
ip addr flush dev eth3

# Create vxlan with explicit local underlay IP
ip link add vxlan10 type vxlan id 10 local 1.1.1.4 dstport 4789
ip link set dev vxlan10 up

brctl addif br0 vxlan10
brctl addif br0 eth0

# Assign underlay IP to uplink
ip addr add 10.1.1.10/30 dev eth3
# Loopback for router-id and BGP source
ip addr add 1.1.1.4/32 dev lo

# FRR config via vtysh -f
vtysh -f /home/jmartos-/Documents/42_WorkSpace/P3/_42user-4.frr
